parameters:
#    mango_api_security.example.class: Mango\API\SecurityBundle\Example

services:
#    mango_api_security.example:
#        class: %mango_api_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
