Mango\API\SecurityBundle\Entity\AccessToken:
    type: entity
    table: access_tokens

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                name: client_id
                referencedColumnName: id
                nullable: false
        user:
            targetEntity: Mango\CoreDomain\Model\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true