Mango\API\SecurityBundle\Entity\AuthCode:
    type: entity
    table: auth_codes

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                nullable: false
        user:
            targetEntity: Sylius\Component\Core\Model\User