Mango\API\SecurityBundle\Entity\RefreshToken:
    type: entity
    table: refresh_tokens

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                nullable: false
        user:
            targetEntity: Mango\CoreDomain\Model\User