Mango\CoreDomainBundle\Document\Category:
    type: document
    referenceable: true

    id:
        fieldName: path
        generator:
            strategy: parent

    parentdocument: phpcrParent
    nodename: name

    fields:
        id:
            uuid: true