Mango\CoreDomainBundle\Document\Image:
    type: document
    referenceable: true

    id:
        fieldName: id
        generator:
            strategy: parent

    parentdocument: parent
    nodename: name

    fields:
        content:
            type: binary
            nullable: true