Mango\CoreDomainBundle\Document\Page:
    type: document
    referenceable: true

    id:
        fieldName: path
        generator:
            strategy: parent

    parentdocument: parent
    nodename: name

    fields:
        id:
            uuid: true
        title:
            type: string
        uri:
            type: string
        description:
            type: string
            nullable: true
        body:
            type: string

    referenceOne:
        image:
            targetEntity: Image