Mango\CoreDomainBundle\Document\Product:
    type: document
    referenceable: true

    id:
        fieldName: path
        generator:
            strategy: parent

    parentdocument: parent
    nodename: name

    fields:
        id:
            uuid: true
        productType:
            type: long
        title:
            type: string
        description:
            type: string
        stock:
            type: long
        price:
            type: double
        retailPrice:
            type: double
            nullable: true

    referenceMany:
        tags:
            strategy: weak
        images:
            strategy: weak

    referenceOne:
        category:
            strategy: weak