#mango_api_docs:
#    resource: "@MangoAPIDocsBundle/Resources/config/routing.yml"
#    prefix:   /

# Version 1.0
mango_api_rest:
    type: rest
    resource: "@MangoAPIRestBundle/Resources/config/routing.yml"
    prefix: /v1

# OAuth2 endpoints
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

# TODO
#fos_oauth_server_authorize:
    #resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"