security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false

        api:
            fos_oauth: true
            stateless: true
            anonymous: true

    # ACL Configuration
    acl:
        connection: default

    # Access Control Rules
    access_control:

        # Protect the whole API, we will always have security context
        #- { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }