mango_api_rest_companies:
    type: rest
    resource: MangoAPIRestBundle:Companies

mango_api_rest_customers:
    type: rest
    resource: MangoAPIRestBundle:Customers

mango_api_rest_users:
    type: rest
    resource: MangoAPIRestBundle:Users

mango_api_rest_routes:
    type: rest
    resource: MangoAPIRestBundle:Routes

mango_api_rest_posts:
    type: rest
    resource: MangoAPIRestBundle:Posts

mango_api_rest_applications:
    type: rest
    resource: MangoAPIRestBundle:Applications