parameters:
    mango_api_rest.action_handler.class: Mango\API\RestBundle\Component\ActionHandler\ActionHandler
    mango_api_rest.result_fetcher.class: Mango\API\RestBundle\Component\ActionHandler\Data\ResultFetcher

services:
    mango_api_rest.action_handler:
        class: %mango_api_rest.action_handler.class%
        arguments: ["@mango_api_rest.result_fetcher"]
        calls:
            - [ setContainer, [@service_container] ]

    mango_api_rest.result_fetcher:
        class: %mango_api_rest.result_fetcher.class%
        arguments: ["@doctrine.orm.entity_manager"]

    mango_api_rest.serializer.json_hal:
        class: Mango\API\RestBundle\Serializer\JsonHalSerializer
        arguments: ["@request_stack"]

    mango_api_rest.lisener.cors:
        class: Mango\API\RestBundle\EventListener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }