parameters:
#    mango_json_api.example.class: Mango\Bundle\JsonApiBundle\Example

services:
#    mango_json_api.example:
#        class: %mango_json_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
