parameters:
#    mango_api_domain.example.class: Mango\API\DomainBundle\Example

services:
#    mango_api_domain.example:
#        class: %mango_api_domain.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
