Mango\CoreDomain\Model\Application:
    type: entity
    table: applications

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        name:
            type: string
            length: 255
            nullable: false

    oneToOne:
        related:
            targetEntity: Mango\CoreDomain\Model\Application
            cascade: ["remove"]
            joinColumns:
                related_id:
                    referencedColumnName: id

    manyToOne:
        company:
            targetEntity: Mango\CoreDomain\Model\Company
            mappedBy: company

    manyToMany:
        modules:
            targetEntity: Module
            joinTable:
                name: application_modules
                joinColumns:
                    application_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    module_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }