Mango\CoreDomain\Model\ApplicationPlatform:
    type: entity
    table: application_platforms

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        type:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        application:
            targetEntity: Mango\CoreDomain\Model\Application
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                application_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
