Mango\CoreDomain\Model\Application:
    type: entity
    table: applications

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        name:
            type: string
            length: 255
            nullable: false

    oneToMany:
        users:
            targetEntity: Mango\CoreDomain\Model\UserApplication
            mappedBy: application

    manyToOne:
        company:
            targetEntity: Mango\CoreDomain\Model\Company
            mappedBy: company
        workspace:
            targetEntity: Mango\CoreDomain\Model\Workspace
        relatedTo:
            targetEntity: Mango\CoreDomain\Model\Application
            unique: false
            cascade: ["remove"]
            joinColumns:
                related_to_id:
                    referencedColumnName: id

    manyToMany:
        modules:
            targetEntity: Module
            joinTable:
                name: application_modules
                joinColumns:
                    application_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    module_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }