Mango\CoreDomain\Model\ApplicationPlatform:
    type: entity
    table: application_platforms
    indexes:
        fk_application_platforms_idx:
            columns:
                - application_id

    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        type:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        application:
            targetEntity: Mango\CoreDomain\Model\Application
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                application_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
