Mango\CoreDomain\Model\Category:
    type: entity
    table: categories

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        name:
            type: string
            length: 128
            nullable: false
        description:
            type: text
            nullable: true

    lifecycleCallbacks: {  }
