Mango\CoreDomain\Model\Employee:
    type: entity
    table: employees

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    oneToOne:
        company:
            targetEntity: Company
        user:
            targetEntity: User

    lifecycleCallbacks: {  }