Mango\CoreDomain\Model\Module:
    type: entity
    table: modules

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        identifier:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: false
            precision: 0
        name:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        parent:
            targetEntity: Mango\CoreDomain\Model\Module
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
