Mango\CoreDomain\Model\Person:
    type: mappedSuperclass

    fields:
        firstName:
            column: first_name
            type: string
            nullable: false
        lastName:
            column: last_name
            type: string
            nullable: false
        phone:
            type: string
            nullable: true
        address:
            type: string
            nullable: true