Mango\CoreDomain\Model\ProductPrice:
    type: entity
    table: product_prices

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        price:
            type: decimal
            scale: 2
            length: null
            unique: false
            nullable: false
            precision: 32
        currency:
            type: string
            scale: 0
            length: 3
            unique: false
            nullable: false
            precision: 0

    lifecycleCallbacks: {  }
