Mango\CoreDomain\Model\UserModule:
    type: entity
    table: user_modules
    indexes:
        fk_user_modules_users_idx:
            columns:
                - user_id
        fk_user_modules_modules_idx:
            columns:
                - module_id
        fk_user_modules_applicaties_idx:
            columns:
                - application_id
    id: {  }
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    oneToOne:
        user:
            targetEntity: Mango\CoreDomain\Model\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        module:
            targetEntity: Mango\CoreDomain\Model\Module
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                module_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        application:
            targetEntity: Mango\CoreDomain\Model\Application
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                application_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
