Mango\CoreDomain\Model\UserApplication:
    type: entity
    table: user_applications

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    manyToOne:
        user:
            targetEntity: Mango\CoreDomain\Model\User
        application:
            targetEntity: Mango\CoreDomain\Model\Application
