Mango\CoreDomain\Model\User:
    type: entity
    table: users

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        username:
            type: string
            length: 255
        usernameCanonical:
            type: string
            length: 255
            unique: true
            column: username_canonical
        email:
            type: string
            length: 255
        emailCanonical:
            type: string
            length: 255
            unique: true
            column: email_canonical
        enabled:
            type: boolean
        salt:
            type: string
        password:
            type: string
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
        expired:
            type: boolean
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
        credentialsExpired:
            type: boolean
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at

    manyToMany:
        applications:
            targetEntity: Application
            joinTable:
                name: user_applications
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    application_id:
                        referencedColumnName: id