Mango\CoreDomain\Model\User:
    type: entity
    table: users

    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID

    fields:
        username:
            type: string
            length: 255
        usernameCanonical:
            type: string
            length: 255
            unique: true
            column: username_canonical
        email:
            type: string
            length: 255
        emailCanonical:
            type: string
            length: 255
            unique: true
            column: email_canonical
        enabled:
            type: boolean
        salt:
            type: string
        password:
            type: string
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
        expired:
            type: boolean
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
        credentialsExpired:
            type: boolean
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        firstName:
            type: string
            nullable: true
            column: first_name
        inbetweener:
            type: string
            nullable: true
            column: inbetweener
        middleName:
            type: string
            nullable: true
            column: middle_name
        lastName:
            type: string
            nullable: true
            column: last_name
        phonePrimair:
            type: string
            nullable: true
            column: phone_primair
        phoneSecundair:
            type: string
            nullable: true
            column: phone_secundair
        streetAddress:
            type: string
            nullable: true
            column: street_address
        streetNumber:
            type: string
            nullable: true
            column: street_number
        streetNumberSuffix:
            type: string
            nullable: true
            column: street_number_suffix
        city:
            type: string
            nullable: true
            column: city
        zipcode:
            type: string
            nullable: true
            column: zipcode
        country:
            type: string
            nullable: true
            column: country
        billingStreetAddress:
            type: string
            nullable: true
            column: billing_street_address
        billingStreetNumber:
            type: string
            nullable: true
            column: billing_street_number
        billingStreetNumberSuffix:
            type: string
            nullable: true
            column: billing_street_number_suffix
        billingCity:
            type: string
            nullable: true
            column: billing_city
        billingZipcode:
            type: string
            nullable: true
            column: billing_cipcode
        billingCountry:
            type: string
            nullable: true
            column: billing_country
        marketingMails:
            type: boolean
            nullable: true
            column: marketing_mails
        notes:
            type: string
            nullable: true
            column: notes

    oneToMany:
        applications:
            targetEntity: Mango\CoreDomain\Model\UserApplication
            mappedBy: user

    manyToMany:
#        applications:
#            targetEntity: Application
#            joinTable:
#                name: user_applications
#                joinColumns:
#                    user_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    application_id:
#                        referencedColumnName: id

        workspaces:
            targetEntity: Workspace
            inversedBy: users
            joinTable:
                name: users_workspaces
                joinColumns:
                  user_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  workspace_id:
                    referencedColumnName: id