Mango\CoreDomain\Model\Product:
    virtual_properties:
        getTitle:
            serialized_name: title
        getPrice:
            serialized_name: price
        getDescription:
            serialized_name: description
        getImages:
            serialized_name: images

    properties:
        detail:
            exclude: true