Mango\CoreDomain\Model\User:
    relations:
        - rel: self
          href:
            route: get_user
            parameters:
                id: expr(object.getId())
            absolute: true

        - rel: applications
          href:
            route: get_user_applications
            parameters:
                id: expr(object.getId())
            absolute: true
#          embedded:
#            content: expr(object.getApplications())

        - rel: workspaces
          href:
            route: get_user_workspaces
            parameters:
                id: expr(object.getId())
            absolute: true
          embedded:
            content: expr(object.getWorkspaces())

        - rel: addresses
          href:
            route: get_user_addresses
            parameters:
                id: expr(object.getId())
            absolute: true

        - rel: new
          href:
            route: new_users
            absolute: true

    properties:
        applications:
            exclude: true
        workspaces:
            exclude: true
        addresses:
            exclude: true