Mango\CoreDomain\Model\Application:
    relations:
        # The application himself
        - rel: self
          href:
            route: get_application
            parameters:
                id: expr(object.getId())
            absolute: true

        # Modules of an application
        - rel: modules
          embedded:
            content: expr(object.getModules())

        # Related applications
        - rel: relatedTo
          href:
            route: get_application
            parameters:
                id: expr(object.getRelatedTo().getId())
            absolute: true
          attributes:
            topLevel: true
            type: applications
          exclusion:
            exclude_if: expr(object.getRelatedTo() === null)
          embedded:
            content: expr(object.getRelatedTo())

        # Pages of an application
        - rel: pages
          href:
            route: get_application_pages
            parameters:
                id: expr(object.getId())
            absolute: true
#          attributes:
#            topLevel: true

        - rel: menus
          href:
            route: get_application_menus
            parameters:
                id: expr(object.getId())
            absolute: true
#          attributes:
#            topLevel: true

        - rel: categories
          href:
            route: get_application_categories
            parameters:
                id: expr(object.getId())
            absolute: true

    properties:
        relatedTo:
            exclude: true
        modules:
            exclude: true
        users:
            exclude: true
            accessor:
                getter: getUsers