Mango\API\DomainBundle\Entity\Customer:
    relations:
        - rel: self
          href:
            route: get_user
            parameters:
                id: expr(object.getId())
            absolute: true
        - rel: users
          href:
            route: get_customer_users
            parameters:
                id: expr(object.getId())
            absolute: true
          embedded:
            content: expr(object.getUsers())

        # Parent customer
        - rel: parent
          href:
            route: get_customer
            parameters:
                id: expr(object.getParent().getId())
            absolute: true
          exclusion:
            exclude_if: expr(object.getParent() == null)
          embedded:
            content: expr(object.getParent())

    properties:
        users:
            exclude: true
        parent:
            exclude: true