Mango\API\DomainBundle\Entity\User:
    relations:
        - rel: self
          href:
            route: get_user
            parameters:
                id: expr(object.getId())
            absolute: true

        - rel: new
          href:
            route: new_users
            absolute: true

    properties:
        customer:
            exclude: true