parameters:
    mango_core_domain.user_repository.doctrine.class: Mango\CoreDomainBundle\Repository\UserRepository
    mango_core_domain.customer_repository.doctrine.class: Mango\CoreDomainBundle\Repository\CustomerRepository
    mango_core_domain.company_repository.doctrine.class: Mango\CoreDomainBundle\Repository\CompanyRepository
    mango_core_domain.application_repository.doctrine.class: Mango\CoreDomainBundle\Repository\ApplicationRepository
    mango_core_domain.workspace_repository.doctrine.class: Mango\CoreDomainBundle\Repository\WorkspaceRepository
    mango_core_domain.page_repository.doctrine.class: Mango\CoreDomainBundle\Repository\PageRepository
    mango_core_domain.module_repository.doctrine.class: Mango\CoreDomainBundle\Repository\ModuleRepository
    mango_core_domain.product_repository.doctrine.class: Mango\CoreDomainBundle\Repository\ProductRepository

services:
    mango_core_domain.user_repository.doctrine:
        class: %mango_core_domain.user_repository.doctrine.class%
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@fos_user.user_manager"]

    mango_core_domain.customer_repository.doctrine:
        class: %mango_core_domain.customer_repository.doctrine.class%
        public: false
        arguments: ["@doctrine.orm.entity_manager"]

    mango_core_domain.company_repository.doctrine:
        class: %mango_core_domain.company_repository.doctrine.class%
        public: false
        arguments: ["@doctrine.orm.entity_manager"]

    mango_core_domain.application_repository.doctrine:
        class: %mango_core_domain.application_repository.doctrine.class%
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@doctrine_phpcr.odm.document_manager"]

    mango_core_domain.workspace_repository.doctrine:
        class: %mango_core_domain.workspace_repository.doctrine.class%
        public: false
        arguments: ["@doctrine.orm.entity_manager"]

    mango_core_domain.module_repository.doctrine:
        class: %mango_core_domain.module_repository.doctrine.class%
        public: false
        arguments: ["@doctrine.orm.entity_manager"]

    # PHPCR
    mango_core_domain.page_repository.doctrine:
        class: %mango_core_domain.page_repository.doctrine.class%
        public: false
        arguments: ["@doctrine_phpcr.odm.document_manager"]

    mango_core_domain.product_repository.doctrine:
            class: %mango_core_domain.product_repository.doctrine.class%
            public: false
            arguments: ["@doctrine_phpcr.odm.document_manager"]