imports:
    - { resource: "doctrine.yml" }

services:
    # Exposed Service
    mango_core_domain.user_repository:
        alias: mango_core_domain.user_repository.doctrine

    mango_core_domain.company_repository:
        alias: mango_core_domain.company_repository.doctrine

    mango_core_domain.customer_repository:
        alias: mango_core_domain.customer_repository.doctrine

    mango_core_domain.application_repository:
        alias: mango_core_domain.application_repository.doctrine

    mango_core_domain.workspace_repository:
        alias: mango_core_domain.workspace_repository.doctrine

    mango_core_domain.page_repository:
        alias: mango_core_domain.page_repository.doctrine

    # Infrasturcture Services
    mango_core_domain.user_service:
        class: Mango\CoreDomainBundle\Service\UserService
        arguments: ["@mango_core_domain.user_repository", "@security.context"]

    mango_core_domain.page_service:
        class: Mango\CoreDomainBundle\Service\PageService
        arguments: ["@mango_core_domain.page_repository", "@form.factory"]