imports:
    - { resource: "doctrine.yml" }

services:
    # Exposed Service
    mango_core_domain.user_repository:
        alias: mango_core_domain.user_repository.doctrine

    mango_core_domain.customer_repository:
        alias: mango_core_domain.customer_repository.doctrine

    mango_core_domain.application_repository:
        alias: mango_core_domain.application_repository.doctrine

    # Infrasturcture Services
    mango_core_domain.user_service:
        class: Mango\CoreDomain\Service\UserService
        arguments: ["@mango_core_domain.user_repository"]