imports:
    - { resource: "doctrine.yml" }

services:
    # Exposed Service
    mango_core_domain.user_repository:
        alias: mango_core_domain.user_repository.doctrine

    mango_core_domain.company_repository:
        alias: mango_core_domain.company_repository.doctrine

    mango_core_domain.customer_repository:
        alias: mango_core_domain.customer_repository.doctrine

    mango_core_domain.application_repository:
        alias: mango_core_domain.application_repository.doctrine

    mango_core_domain.workspace_repository:
        alias: mango_core_domain.workspace_repository.doctrine

    mango_core_domain.page_repository:
        alias: mango_core_domain.page_repository.doctrine

    mango_core_domain.module_repository:
        alias: mango_core_domain.module_repository.doctrine

    mango_core_domain.product_repository:
        alias: mango_core_domain.product_repository.doctrine

    mango_core_domain.category_repository:
        alias: mango_core_domain.category_repository.doctrine

    mango_core_domain.shopproduct_repository:
        alias: mango_core_domain.shopproduct_repository.doctrine

    mango_core_domain.employee_repository:
        alias: mango_core_domain.employee_repository.doctrine

    # Infrasturcture Services
    mango_core_domain.user_service:
        class: Mango\CoreDomainBundle\Service\UserService
        arguments: ["@mango_core_domain.user_repository", "@security.context", "@form.factory"]

    mango_core_domain.company_service:
            class: Mango\CoreDomainBundle\Service\CompanyService
            arguments: [@mango_core_domain.company_repository, @form.factory]

    mango_core_domain.page_service:
        class: Mango\CoreDomainBundle\Service\PageService
        arguments: ["@mango_core_domain.page_repository", "@mango_core_domain.application_repository", "@router", "@form.factory"]

    mango_core_domain.product_service:
        class: Mango\CoreDomainBundle\Service\ProductService
        arguments: ["@mango_core_domain.product_repository", "@form.factory"]

    mango_core_domain.category_service:
        class: Mango\CoreDomainBundle\Service\CategoryService
        arguments: ["@mango_core_domain.category_repository", "@form.factory"]

    mango_core_domain.shopproduct_service:
        class: Mango\CoreDomainBundle\Service\ShopproductService
        arguments: [@mango_core_domain.shopproduct_repository, @form.factory]

    mango_core_domain.employee_service:
        class: Mango\CoreDomainBundle\Service\EmployeeService
        arguments: [@mango_core_domain.employee_repository, @form.factory]


    # Form types
    mango_core_domain.type.mango_repository:
        class: Mango\CoreDomainBundle\Form\Type\MangoRepositoryType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: mango_repository }