# We define the validation rules for our domain models in here

Mango\CoreDomain\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: "The username you entered already exists."
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: "This email is already in use."
    properties:
        username:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: ~

Mango\CoreDomain\Model\Customer:
    properties:
        company:
            - NotBlank: ~

Mango\CoreDomain\Model\Company:
    properties:
        name:
            - NotBlank: ~

Mango\CoreDomain\Model\Page:
    properties:
        name:
            - NotBlank: ~
        uri:
            - NotBlank: ~
        title:
            - NotBlank: ~
        body:
            - NotBlank: ~
        application:
            - NotBlank: ~

Mango\CoreDomain\Model\Product:
    properties:
        productType:
            - NotBlank: ~
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        price:
            - NotBlank: ~
        stock:
            - NotBlank: ~
        category:
            - NotBlank: ~

Mango\CoreDomain\Model\StoreProduct:
    properties:
        workspace:
            - NotBlank: ~

Mango\CoreDomain\Model\ShopProduct:
    properties:
        application:
            - NotBlank: ~

Mango\CoreDomain\Model\Category:
    properties:
        application:
            - NotBlank: ~
        name:
            - NotBlank: ~